version:  "3.8"

services:
  node-app:
    build:
      context: ./app
      dockerfile:  Dockerfile
    container_name:  node-app
    ports:
      -  "3000:3000"
    env_file:
      -  ./app/backEnd/.env
    
    depends_on:
      mongo:
        condition: service_healthy
    
    networks:
      -  frontend-net
      -  backend-net
  
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always

    env_file:
      - ./app/backEnd/.env
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-express

    restart: always

    ports:
      - "8081:3000"

    env_file:
      - ./app/backEnd/.env

    depends_on:
      mongo:
        condition: service_healthy

    networks:
      - backend-net
  
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy

    ports:
      - "8080:8080"

    env_file:
      - ./app/backEnd/.env

    environment:
      - ADMIN_IP=${ADMIN_IP}

    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    
    depends_on:
      - node-app
    
    networks:
      - frontend-net

volumes:
  mongo-data:

networks:
  frontend-net:
  backend-net:

